networks:
  modx:

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/local.Dockerfile
      args:
        LOCAL_LINUX_USER: ${LOCAL_LINUX_USER:-0}
        LOCAL_LINUX_USER_UID: ${LOCAL_LINUX_USER_UID:-0}
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../modx/.:/var/www/html:delegated
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - modx

  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql:delegated
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - modx

  php:
    build:
      context: .
      dockerfile: ./local.Dockerfile
      args:
        LOCAL_LINUX_USER: ${LOCAL_LINUX_USER:-0}
        LOCAL_LINUX_USER_UID: ${LOCAL_LINUX_USER_UID:-0}
    container_name: php
    volumes:
      - ../modx/.:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - modx
    depends_on:
      - mysql